on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
         
      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Run the Gradle Build (skip tests + ktlint)
        run: ./gradlew build -x test -x ktlintCheck -x ktlintFormat --exclude-task ktlintMainSourceSetCheck --exclude-task ktlintTestSourceSetCheck --exclude-task runKtlintCheckOverKotlinScripts --exclude-task runKtlintCheckOverMainSourceSet --exclude-task runKtlintCheckOverTestSourceSet

      # Runs the Gradle test task
      - name: Test with Gradle
        run: ./gradlew test --tests "*"

      # Builds a zip file with the JUnit test report
      - name: Archive test report
        uses: actions/upload-artifact@v4.4.2
        with:
          name: Test report
          path: build/reports/tests/test

      # Builds a zip file with the code coverage report
      - name: Archive coverage report
        uses: actions/upload-artifact@v4.4.2
        with:
          name: Code Coverage report
          path: build/reports/jacoco/test/html

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/*.jar

  documentation:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checks out repository
      - uses: actions/checkout@v4

      # Runs Dokka
      - name: Dokka with Gradle
        run: ./gradlew dokkaHtml

      # Uploads the KDoc documentation site
      - name: Archive KDoc Documentation
        uses: actions/upload-artifact@v4.4.2
        with:
          name: KDoc Documentation Site
          path: build/dokka/html

